arch:
 - amd64
 - ppc64le
 
addons:
  apt:
    packages:
      - lynx

language: java
sudo: false

jdk:
  - openjdk11
  - openjdk8

script:
  - ./gradlew --debug

after_failure:
  - if [ -f /home/travis/build/Netflix/Hystrix/hystrix-core/build/reports/tests/test/index.html ]; then lynx -dump /home/travis/build/Netflix/Hystrix/hystrix-core/build/reports/tests/test/index.html; fi
